version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: bootcamp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boarddb
      MYSQL_USER: sa
      MYSQL_PASSWORD: Dev@2024@1234
    ports:
      - "3306:3306"